language: php

dist: trusty

services:
  - docker

matrix:
  include:
    - php: 7.4

# https://docs.travis-ci.com/user/docker/#using-docker-compose
# https://github.com/docker/compose/issues/6268
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

#install

before_script:
  - cp -p .env{.example,}
  - composer require php-coveralls/php-coveralls:^2.1.0
  - composer install -n

script:
  - docker-compose run --rm mx vendor/bin/phpunit --coverage-clover clover.xml

#before_cache

after_success:
  - ls -la .
  - vendor/bin/php-coveralls --coverage_clover=clover.xml --json_path=coveralls-upload.json  -v
