language: php

dist: trusty

services:
  - redis-server

matrix:
  include:
    - php: 7.3
    - php: 7.4
      env: ANALYSIS='true'
    - php: nightly

  allow_failures:
    - php: nightly

before_script:
  - cp -p .env{.example,}
  - sed -i -e 's/REDIS_NAME=.*/REDIS_NAME=localhost/g' .env
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer require php-coveralls/php-coveralls:^2.2
  - composer install -n

script:
  - |
    if [[ "${ANALYSIS}" == 'true' ]]; then
      composer analyze
    fi
  - |
    if [[ "${ANALYSIS}" == 'true' ]]; then
      vendor/bin/phpunit --coverage-clover logs/clover.xml
    fi
after_success:
  - |
    if [[ "${ANALYSIS}" == 'true' ]]; then
      vendor/bin/php-coveralls --coverage_clover=logs/clover.xml --json_path=logs/coveralls-upload.json  -v
    fi
