version: '3.7'

volumes:
    logs:
        driver: local

services:
    mx:
        build: ./docker/php
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        depends_on:
            - redis
        networks:
            - backend
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs

    redis:
        env_file: .env
        hostname: ${REDIS_NAME}
        image: redis:alpine
        networks:
            - backend
        expose:
            - ${REDIS_PORT}

networks:
    backend:
