#!/usr/bin/env php
<?php declare(strict_types=1);

use App\Utils\CommandInvoker;
use DI\Container;
use Dotenv\Dotenv;
use Slim\App;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Output\ConsoleOutput;

require __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv::create(__DIR__);
$dotenv->load();

$app = require __DIR__ . '/app/bootstrap.php';
assert($app instanceof App);

$container = $app->getContainer();
assert($container instanceof Container);

$bootstrap = new CommandInvoker($container, new Application(), new ConsoleOutput());
$bootstrap->__invoke('App\Application\Commands');
